version: "3.0"

services:
  permissions-service:
    container_name: permissions-service
    image: local/permissions-service:test
    environment:
      - NODE_ENV=test
      - PORT=80
      - MONGO_DB=myappdatabase
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DBINDEX=0
    command: npm test
    tty: true
    volumes:
      - "../:/var/www"
      - /var/www/node_modules
    ports:
      - 8098:80
    stdin_open: true
    networks:
      - services
      - db
      - cache

networks:
  services:
    external: true
  db:
    external: true
  cache:
    external: true
