version: "3.0"

services:
  permissions-service:
    container_name: permissions-service
    image: local/permissions-service:dev
    tty: true
    command: bash
    volumes:
      - "../:/var/www/"
    ports:
      - 8098:80
    stdin_open: true
    networks:
      - services
      - db
      - cache

networks:
  services:
    external: true
  db:
    external: true
  cache:
    external: true
