version: "3.0"

services:
  permissions-service:
    container_name: permissions-service
    image: local/permissions-service:test
    command: npm test
    tty: true
    volumes:
      - "../config/app.conf.json:/var/www/config/app.conf.json"
      - /var/www/node_modules
    ports:
      - 8098:80
    stdin_open: true
    networks:
      - services
      - db
      - cache

networks:
  services:
    external: true
  db:
    external: true
  cache:
    external: true
