version: "3.0"

services:
  database:
    container_name: database
    image: mongo:4-xenial
    networks:
      - db

  cache:
    container_name: cache
    image: redis:3.0.6-32bit
    networks:
      - cache
    logging:
      driver: none

networks:
  db:
    external: true
  cache:
    external: true
